Todo Lists In JavaScript
karthykarthick/To-Do-List-Js pull request #1
Opened 2021-02-15 22:13 UTC by karthykarthick

In this user can
- create, 
- read, 
- update,
-  delete lists it will save local storage.

2021-02-15 23:03 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi team :hand: 
Awesome job on this project so far :clap: 
But we need to make some changes before moving on.

- [ ] You did a nice job setting up the linter on the PR using Github actions. However, it was not properly set up in your repository. We need to follow the instructions [here](https://github.com/microverseinc/linters-config/tree/master/javascript) and add `eslint` and it's needed dependencies as devDependencies. The linter should be used in the development stages, It helps us developers to follow good practice and to maintain clean code.

- [ ] We need to remove all `eslint-disable` commented lines from your code to make it accordingly with the linter rules. Instead of disabling it, we need to use the recommended approach. You can google it to learn more about the rule and how you can solve the error. [Example](https://eslint.org/docs/rules/linebreak-style). Setting up `eslint` on your repo it will help you to avoid these errors.

- [ ] As the requirements said, the application should have a default Project already created.

Happy coding :computer: 
**Sergio Torres**

2021-02-15 23:03 UTC, Torres-ssf commented on src/components/Todos.js
> +      // e.preventDefault();
- [ ] We need to remove all commented code.

2021-02-15 23:03 UTC, Torres-ssf commented on src/components/Ui.js
> +      // todos.completedTask()
- [ ] We need to remove all commented code

2021-02-15 23:03 UTC, Torres-ssf commented on package.json
> +  "homepage": "https://github.com/karthykarthick/To-Do-List-Js#readme",
- [ ] The homepage property is duplicated at the package.json file.

2021-02-15 23:40 UTC, bellom commented
> ### Changes required 💪
> Hi team ✋
> Awesome job on this project so far 👏
> But we need to make some changes before moving on.
> 
> * [ ]  You did a nice job setting up the linter on the PR using Github actions. However, it was not properly set up in your repository. We need to follow the instructions [here](https://github.com/microverseinc/linters-config/tree/master/javascript) and add `eslint` and it's needed dependencies as devDependencies. The linter should be used in the development stages, It helps us developers to follow good practice and to maintain clean code.
> * [ ]  We need to remove all `eslint-disable` commented lines from your code to make it accordingly with the linter rules. Instead of disabling it, we need to use the recommended approach. You can google it to learn more about the rule and how you can solve the error. [Example](https://eslint.org/docs/rules/linebreak-style). Setting up `eslint` on your repo it will help you to avoid these errors.
> * [ ]  As the requirements said, the application should have a default Project already created.
> 
> Happy coding 💻
> **Sergio Torres**

@karthykarthick @kcotrinam, I think you guys miss the second comment from @Torres-ssf.
Kindly work on it.

2021-02-15 23:46 UTC, bellom requested changes
## Hi Team  :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

**According to @Torres-ssf, you have told to remove Eslint inline comment, kindly attend to it.**

**_In other words;_**
You are not modifying linter config files directly, but you are disabling many ESLint rules with the inline Eslint comments in your codebase, and that's kind of bypassing ESLint configuration which represent style guidelines that you share with your team - which is a group of all Microverse students. (screenshot from Pathwright).

 Please remove ESLint disabling rules comments and fix your code accordingly.
I'm sure this is not going to be an issue for you, you got this 💪.

Remember that you can run ESLint locally to debug the issues and fix them before pushing, and you probably have already installed the VSCode ESLint extension if you're using VSCode, which can be also very helpful.

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-02-15 23:46 UTC, bellom commented on src/components/Project.js
> +/* eslint-disable linebreak-style */
Please remove ESLint disabling rules comments

2021-02-15 23:46 UTC, bellom commented on src/components/Todos.js
> +/* eslint-disable linebreak-style */
Please remove ESLint disabling rules comments

2021-02-15 23:46 UTC, bellom commented on src/components/Ui.js
> +/* eslint-disable linebreak-style */
Please remove ESLint disabling rules comments

2021-02-15 23:46 UTC, bellom commented on src/components/storage.js
> +/* eslint-disable linebreak-style */
Please remove ESLint disabling rules comments

2021-02-15 23:46 UTC, bellom commented on src/index.js
> +/* eslint-disable linebreak-style */
Please remove ESLint disabling rules comments

2021-02-16 09:08 UTC, mikenath223 requested changes
### Hello Team 👋

**You've done pretty well here fixing a few issues raised in the previous review. 👌**

However, let's make a couple of changes.

- [ ] Kindly link the `index.js` in the `index.html` this provides a way to run the project after bundling the modules with webpack. 

- Please refer to comments on the code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-02-16 09:09 UTC, mikenath223 commented on src/components/Todos.js
> +// };
- [ ] Please remove this commented code block. Kindly use git history if you want to refer to previous code versions.

2021-02-16 09:10 UTC, mikenath223 commented on src/components/Ui.js
> +    // todos.completedTask();
- [ ] Also kindly remove this commented code.

2021-02-16 15:11 UTC, Torres-ssf approved these changes
### PR Approved :+1: 
Hello again team :hand: 
You may merge the PR
Good luck with the next project

Happy coding :computer: 
**Sérgio Torres**

2021-02-16 17:11 UTC, merged